name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t husnifd/api-jelajah-medika .
      - name: Run Unit Tests
        run: docker run husnifd/api-jelajah-medika python -m unittest discover tests
      - name: Publish image to docker hub
        run: docker push husnifd/api-jelajah-medika:latest  

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull husnifd/api-jelajah-medika:latest
      - name: Delete Old Container
        run: sudo docker rm -f apiJelajahMedikaContainer
      - name: Run docker container
        run: sudo docker run -d -p 6000:6000 --name apiJelajahMedikaContainer husnifd/api-jelajah-medika
      - name: Delete Not Associate Image
        run: sudo docker image prune -af